### ISSUE TITLE
Getting an error "./configure: line 407: pr: command not found" when building using the scripts

### ISSUE THREAD

**Issue by Hirshfeld** [shutup/ffmpeg4android#1]
Here's the output:
~FFMPEG>build_android_one_file_140721.sh
Welcome to Git (version 1.9.4-preview20140815)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
./configure: line 407: pr: command not found
~android-ndk-r10d/toolchains/arm-linux-androideabi-4.8/prebui
lt/linux-x86_64/bin/arm-linux-androideabi-gcc is unable to create an executable
file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
~FFMPEG\build_android_one_file_140721.sh: line 54: make
: command not found
~FFMPEG\build_android_one_file_140721.sh: line 55: make
: command not found
~FFMPEG\build_android_one_file_140721.sh: line 56: make
: command not found
~FFMPEG\build_android_one_file_140721.sh: line 57: C:/P
rograms/Android/android-ndk-r10d/toolchains/arm-linux-androideabi-4.8/prebuilt/l
inux-x86_64/bin/arm-linux-androideabi-ar: No such file or directory
~FFMPEG\build_android_one_file_140721.sh: line 58: C:/P
rograms/Android/android-ndk-r10d/toolchains/arm-linux-androideabi-4.8/prebuilt/l
inux-x86_64/bin/arm-linux-androideabi-ld: No such file or directory

**Comment by shutup** [comment]
sorry ,maybe too late to answer back. Are you running this script in an Windows OS .THE Script is prefer to be running in an Unix like OS .
in unix like OS:
sudo apt-get --quiet --yes install build-essential git autoconf libtool pkg-config gperf gettext yasm
also the NDK installed.

**Comment by lhwang** [comment]
Hi Ori,
Have you resolved this issue? I am facing exactly the same issue with you. Could you please tell me the progress?

Thank you very much!

**Comment by Hirshfeld** [comment]
Eventually I dumped ffmpeg, it wasn't stable enough and it was a real struggle.  I switched to opengl. opengl was more fit to the job, I was looking for a way to encode bitmaps over videos on android.

**Comment by lhwang** [comment]
Thank you very much for your reply!  You mean you gave up ffmpeg? I need to cross-compile ffmpeg on windows for qnx.  It is really a struggle!

**Comment by Hirshfeld** [comment]
i gave it up... switched to opengl. perhaps there is also an alternative solution for your problem, rather than ffmpeg:)

**Comment by lhwang** [comment]
OK, I will learn something about opengl. thank you for your advice!

**Comment by shutup** [comment]
@lhwang make sure the build environment is complete. and just search the error msg, you will find the answer. Or you can build it under ubuntu in an virtualbox

**Comment by lhwang** [comment]
@shutup Hi Xiaoren, 
May I know do you have a successful case of building ffmpeg for qnx on window or linux? What do you mean by "complete"? I have a qnx6.5 momentics IDE on win7 and I used sh.exe/ksh.exe it provided but
many commands of Linux not found. I appreciate if you can me more details about your experience about the cross-compiling.

**Comment by shutup** [comment]
@lhwang my success case is on unix like system,and for arm platform.as for cross-compile,you need first know what the target platform is, and find the toolchain for your target platform. you mention qnx ,i am not familar with it. but it should dot the same.For example, cross-complie for android, you need android ndk it contains android related toolchains, then my device running android is arm based ,the cpu is qualcomm 801. then i can get the source ,and configure it ,then build it use ndk toolchain. in win7 you may need MSYS/MinGW to get all linux cmd you need, but i do not like this way .i prefer you setup an ubuntu on virtualbox.

**Comment by shutup** [comment]
@lhwang you should serach ffmpeg + qnx, before you start. And some post may have some help.

**Comment by lhwang** [comment]
@shutup Thank you for your detaild information. Thanks a lot!

**Comment by xzKinGzxBuRnzx** [comment]
Ran into this issue, fix by installing `coreutils`

**Comment by NetherGranite** [comment]
> Ran into this issue, fix by installing `coreutils`

This also worked for me @xzKinGzxBuRnzx . It turns out you can easily do this in the command line: `mingw-get install msys-coreutils`

**Comment by afturner** [comment]
For others, arriving here because of Docker and Alpine linux, installing `coreutils` per @xzKinGzxBuRnzx did indeed fix the problem. 

I think this can be closed?
